#!/bin/sh
echo "# Dale\n\n## 2.1 introspection\n" > doc/2-1-introspection.md
./module-to-markdown < modules/introspection.dt >> doc/2-1-introspection.md
echo "# Dale\n\n## 2.2 ctype\n" > doc/2-2-ctype.md
./module-to-markdown < modules/ctype.dt >> doc/2-2-ctype.md
echo "# Dale\n\n## 2.3 math\n" > doc/2-3-math.md
./module-to-markdown < modules/math.dt >> doc/2-3-math.md
echo "# Dale\n\n## 2.4 macros-core\n" > doc/2-4-macros-core.md
./module-to-markdown < modules/macros-core.dt >> doc/2-4-macros-core.md
echo "# Dale\n\n## 2.5 stdlib\n" > doc/2-5-stdlib.md
./module-to-markdown < modules/stdlib.dt >> doc/2-5-stdlib.md
echo "# Dale\n\n## 2.6 macros\n" > doc/2-6-macros.md
./module-to-markdown < modules/macros.dt >> doc/2-6-macros.md
echo "# Dale\n\n## 2.7 assert\n" > doc/2-7-assert.md
./module-to-markdown < modules/assert.dt >> doc/2-7-assert.md
echo "# Dale\n\n## 2.8 concepts-core\n" > doc/2-8-concepts-core.md
./module-to-markdown < modules/concepts-core.dt >> doc/2-8-concepts-core.md
echo "# Dale\n\n## 2.9 concept-defs\n" > doc/2-9-concept-defs.md
./module-to-markdown < modules/concept-defs.dt >> doc/2-9-concept-defs.md
echo "# Dale\n\n## 2.10 concepts\n" > doc/2-10-concepts.md
./module-to-markdown < modules/concepts.dt >> doc/2-10-concepts.md
echo "# Dale\n\n## 2.11 utility\n" > doc/2-11-utility.md
./module-to-markdown < modules/utility.dt >> doc/2-11-utility.md
echo "# Dale\n\n## 2.12 derivations\n" > doc/2-12-derivations.md
./module-to-markdown < modules/derivations.dt >> doc/2-12-derivations.md
echo "# Dale\n\n## 2.18 array\n" > doc/2-18-array.md
./module-to-markdown < modules/array.dt >> doc/2-18-array.md
