#!/bin/sh
if [ "$1" != "" ]
then
    export DALE_TEST_DIR=$1
else
    export DALE_TEST_DIR=.
fi
if [ "$DALE_TEST_ARGS" = "" ]
then
    export DALE_TEST_ARGS=-O3
fi
PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0)" ${DALE_TEST_DIR}/t/*/*.t
